export const WORKS = [
  { file: "AKI.png", title: "AKI", category: "Плакат" },
  { file: "Blue.png", title: "Blue", category: "Иллюстрация" },
  { file: "COWBOY.png", title: "Cowboy", category: "Плакат" },
  { file: "Dance.png", title: "Dance", category: "Плакат" },
  { file: "FOOD.png", title: "Food", category: "Плакат" },
  { file: "FROGPHONE.png", title: "Frogphone", category: "Иллюстрация" },
  { file: "FUCK THIS.png", title: "Fuck This", category: "Плакат" },
  { file: "FUCKED UP.png", title: "Fucked Up", category: "Плакат" },
  { file: "GoodPals.png", title: "Good Pals", category: "Плакат" },
  { file: "Knight.png", title: "Knight", category: "Иллюстрация" },
  { file: "Lemon.png", title: "Lemon", category: "Плакат" },
  { file: "Need Space.png", title: "Need Space", category: "Плакат" },
  { file: "NEVER.png", title: "Never", category: "Плакат" },
  { file: "Orange.png", title: "Orange", category: "Иллюстрация" },
  { file: "RIDE.png", title: "Ride", category: "Плакат" },
  { file: "WHO.png", title: "Who", category: "Плакат" },
  { file: "Add colors.jpg", title: "Add Colors", category: "Плакат" },
  { file: "RESENTMENT@2x.png", title: "Resentment", category: "Плакат" },
  { file: "Tell time.png", title: "Tell Time", category: "Плакат" },
  { file: "Frame 14.png", title: "Frame 14", category: "Коллаж" },
  { file: "Балид.jpg", title: "Балид", category: "Плакат" },
  { file: "Банер.jpg", title: "Банер", category: "Баннер" },
  { file: "Басочек.jpg", title: "Басочек", category: "Иллюстрация" },
  { file: "Баухаус.png", title: "Баухаус", category: "Плакат" },
  { file: "Визитка.png", title: "Визитка", category: "Полиграфия" },
  { file: "Время.png", title: "Время", category: "Плакат" },
  { file: "Интернет.jpg", title: "Интернет", category: "Плакат" },
  { file: "Кофейек.jpg", title: "Кофейек", category: "Иллюстрация" },
  { file: "Лемончек.jpg", title: "Лемончек", category: "Иллюстрация" },
  { file: "Летов__.jpg", title: "Летов", category: "Плакат" },
  { file: "Лягушки.jpg", title: "Лягушки", category: "Иллюстрация" },
  { file: "Маяк.jpg", title: "Маяк", category: "Плакат" },
  { file: "Меню для ресторана.png", title: "Меню для ресторана", category: "Полиграфия" },
  { file: "Пицца.jpg", title: "Пицца", category: "Плакат" },
  { file: "Прикол.jpg", title: "Прикол", category: "Плакат" },
  { file: "Разнообразие.jpg", title: "Разнообразие", category: "Плакат" },
  { file: "Фэшен.png", title: "Фэшен", category: "Плакат" },
];
